

export const SCRIPTS = [
  { name: "train_qwen_image.py", type: "old" },
  { name: "train_flux_lora_ui_kontext_new.py", type: "old" },
  { name: "train_longcat.py", type: "new" },
  { name: "train_longcat_edit.py", type: "new" },
  { name: "train_qwen_image_edit_new.py", type: "new" },
];

export const OPTIMIZERS = ["adamw", "prodigy", "adamw8bit"];
export const SCHEDULERS = ["linear", "cosine", "constant", "constant_with_warmup"];
export const PRECISIONS = ["no", "fp16", "bf16"];
export const WEIGHTING_SCHEMES = ["sigma_sqrt", "logit_normal", "mode", "cosmap", "logit_snr"];
export const DEFAULT_GLOBAL_CONFIG = {
  pretrained_model_name_or_path: "F:/T2ITrainer_pulic/T2ITrainer/longcat_models/LongCat-Image-Edit",
  output_dir: "F:/ImageSet/longcat_test_edit_output",
  logging_dir: "/home/waas/kontext_output/logs",
  save_name: "test_edit",
  train_data_dir: "F:/ImageSet/longcat",
  model_path: "",
  vae_path: "",
  rank: 16,
  rank_alpha: 16,
  use_lokr: false,
  lokr_factor: 8,
  lora_layers: "all",
  train_batch_size: 1,
  learning_rate: 1e-4,
  num_train_epochs: 10,
  save_model_epochs: 1,
  resolution: "1024",
  mixed_precision: "bf16",
  seed: 4321,
  gradient_checkpointing: true,
  optimizer: "adamw",
  caption_dropout: 0.1,
  recreate_cache: false,
  validation_epochs: 1,
  validation_ratio: 0.1,
  guidance_scale: 1.0,
  weighting_scheme: "logit_normal",
  logit_mean: 0.0,
  logit_std: 1.0,
  mode_scale: 1.29,
  blocks_to_swap: 10,
  mask_dropout: 0.0,
  freeze_transformer_layers: "",
  freeze_single_transformer_layers: ""
};

export const TRANSLATIONS = {
  en: {
    palette: "Nodes",
    output: "Preview",
    save: "Save Workflow",
    load: "Workflow",
    undo: "Undo",
    redo: "Redo",
    core: "Core Nodes",
    structure: "Structure",
    components: "Components",
    old_schema: "Old Schema",
    cmd: "Command",
    json: "JSON Config",
    copy: "Copy",
    about: "About",
    // Nodes
    script: "Script Loader",
    template: "Config Template",
    old_root: "Old Schema Root",
    dir: "Directory Setup",
    lora: "LoRA Config",
    misc: "Miscellaneous Settings",
    ds_list: "Dataset List",
    ds_conf: "Dataset Configuration",
    img_list: "Image List",
    img_item: "Image Item",
    tgt_list: "Target List",
    tgt_item: "Target Item",
    ref_list: "Reference List",
    ref_item: "Reference Group",
    ref_src: "Reference Source",
    cap_list: "Caption List",
    cap_item: "Caption Item",
    batch_list: "Batch List",
    batch_item: "Batch Item",
    // Old Schema Nodes
    old_image_list: "Image Config List (Old)",
    old_image_item: "Image Item (Old)",
    old_caption_list: "Caption Config List (Old)",
    old_caption_item: "Caption Item (Old)",
    old_ref_list: "Reference Image List (Old)",
    old_ref_item: "Reference Image Item (Old)",
    old_train_list: "Training Set List (Old)",
    old_train_item: "Training Set Item (Old)",
    old_layout_list: "Layout List (Old)",
    old_layout_item: "Layout Item (Old)",

    // Fields
    python_script: "Python Script",
    config_path: "Config Path (Output)",
    pretrained_path: "Pretrained Model Path",
    output_dir: "Output Directory",
    logging_dir: "Logging Directory",
    save_name: "Save Name",
    global_data_dir: "Global Data Directory",
    model_path: "Model Path (Optional)",
    vae_path: "VAE Path (Optional)",
    rank: "Rank",
    alpha: "Alpha",
    use_lokr: "Use LoKR",
    lokr_factor: "LoKR Factor",
    lora_layers: "LoRA Layers (Comma Separated)",
    mask_dropout: "Mask Dropout",
    freeze_transformers: "Freeze Transformers (CSV)",
    resolution: "Resolution",
    batch_size: "Batch Size",
    epochs: "Epochs",
    learning_rate: "Learning Rate",
    optimizer: "Optimizer",
    precision: "Precision",
    scheduler: "Scheduler",
    seed: "Seed",
    cap_dropout: "Caption Dropout",
    save_every: "Save Every N Epochs",
    blocks_to_swap: "Blocks to Swap",
    grad_chkpt: "Gradient Checkpointing",
    recr_cache: "Recreate Cache",
    val_epochs: "Validation Epochs",
    val_ratio: "Validation Ratio",
    weighting_scheme: "Weighting Scheme",
    logit_mean: "Logit Mean",
    logit_std: "Logit Standard Deviation",
    mode_scale: "Mode Scale",
    guidance_scale: "Guidance Scale",

    key: "Key",
    suffix: "Suffix",
    image_key: "Image Key",
    from_key: "From Key (Optional)",
    ext: "Extension",
    image: "Image",
    include_ref: "Include Reference List",
    target: "Target",
    caption: "Caption",
    reference: "Reference (Optional)",
    group_key: "Group Key",
    sample_type: "Sample Type",
    data_dir: "Data Directory",
    repeats: "Repeats",
    recreate_cache_target: "Target",
    recreate_cache_ref: "Reference",
    recreate_cache_cap: "Caption",
    image_config_list: "Image Config List",
    caption_config_list: "Caption Config List",
    target_config_list: "Target Config List",
    reference_config_list: "Reference Config List",
    batch_config_list: "Batch Config List",
    training_set_list: "Training Set List",
    from_script: "From Script",
    from_dataset: "From Dataset",
    from_ds_list: "From DS List",
    from_list: "From List",
    from_group: "From Group",
    from_root: "From Root",
    from_item: "From Item",
    to_dir: "To Directory",
    to_lora: "To LoRA",
    to_misc: "To Miscellaneous",
    to_template: "To Template",
    to_ds_list: "To Dataset List",
    to_old_schema: "To Old Schema",
    connect_items: "Connect items from here.",
    connect_multiple: "Connect multiple datasets from here.",
    paste_template: "Paste base JSON or select template to merge defaults.",
    item: "Item",
    dataset: "Dataset",
    add_slot: "Add Slot",
    add_source: "Add Source",
    advanced_settings: "Advanced Settings",
    ref_config_key: "Reference Config Key",
    resize: "Resize",
    min_len: "Minimum Length",
    dropout: "Dropout",
    count: "Count",
    instruction: "Instruction",
    noised: "Noised",
    captions_selection_target: "Captions Target",

    // New specific labels
    image_name: "Image Name",
    target_name: "Target Name",
    from_image: "From Image",
    reference_name: "Reference Name",
    caption_name: "Caption Name",
    
    // Workflow Panel
    workflow_panel: "Workflow Panel",
    current_workflow: "Current Workflow",
    save_current: "Save",
    save_as_template: "Save As Template",
    available_templates: "Available Templates",
    search_templates: "Search templates...",
    loading_templates: "Loading templates...",
    no_templates_found: "No templates found",
    load: "Load",
    delete_template: "Delete template",
    enter_template_name: "Enter template name:",
    confirm_clear_nodes: "Are you sure you want to clear all nodes?",
    confirm_delete_template: "Are you sure you want to delete \"{templateName}\"?",
    
    // Contact Information Labels
    twitter: "Twitter",
    email: "Email",
    qq_group: "QQ Group",
    wechat_id: "WeChat ID",
    civitai: "CivitAI",
    bilibili: "Bilibili",
    
    // About Panel Content
    t2itrainer_repository: "T2ITrainer Repository",
    contact_information: "Contact Information",
    sponsor_message: "Sponsor me for more open source projects",
    buy_me_a_coffee: "Buy me a coffee",
    wechat: "WeChat",
    node_documentation: "Node documentation",
    documentation_description: "The following documentation details the inputs and configuration fields for every node type in the editor.",
    core_nodes: "Core Nodes",
    structure_nodes: "Structure Nodes (New Schema)",
    component_nodes: "Component Nodes",
    old_schema_nodes: "Old Schema Nodes",
    
    // About Panel Tabs
    about_tab: "About",
    docs_tab: "Docs",
  },
  cn: {
    palette: "节点",
    output: "预览",
    save: "保存工作流",
    load: "工作流",
    undo: "撤销",
    redo: "重做",
    core: "核心节点",
    structure: "结构",
    components: "组件",
    old_schema: "旧版架构",
    cmd: "运行命令",
    json: "JSON 配置",
    copy: "复制",
    about: "关于",
    // Nodes
    script: "脚本加载器",
    template: "配置模板",
    old_root: "旧版架构根节点",
    dir: "目录设置",
    lora: "LoRA配置",
    misc: "杂项参数",
    ds_list: "数据集列表",
    ds_conf: "数据集配置",
    img_list: "图片列表",
    img_item: "图片项",
    tgt_list: "目标列表",
    tgt_item: "目标项",
    ref_list: "参考列表",
    ref_item: "参考组",
    ref_src: "参考来源",
    cap_list: "标注列表",
    cap_item: "标注项",
    batch_list: "批次列表",
    batch_item: "批次项",
    // Old Schema Nodes
    old_image_list: "图片配置列表 (旧)",
    old_image_item: "图片项 (旧)",
    old_caption_list: "标注配置列表 (旧)",
    old_caption_item: "标注项 (旧)",
    old_ref_list: "参考图列表 (旧)",
    old_ref_item: "参考图项 (旧)",
    old_train_list: "训练集列表 (旧)",
    old_train_item: "训练集项 (旧)",
    old_layout_list: "布局列表 (旧)",
    old_layout_item: "布局项 (旧)",

    // Fields
    python_script: "Python 脚本",
    config_path: "配置路径 (输出)",
    pretrained_path: "预训练模型路径",
    output_dir: "输出目录",
    logging_dir: "日志目录",
    save_name: "保存名称",
    global_data_dir: "全局数据目录",
    model_path: "模型路径 (可选)",
    vae_path: "VAE 路径 (可选)",
    rank: "秩 (Rank)",
    alpha: "Alpha",
    use_lokr: "使用 LoKR",
    lokr_factor: "LoKR 因子",
    lora_layers: "LoRA 层 (逗号分隔)",
    mask_dropout: "掩码 Dropout",
    freeze_transformers: "冻结 Transformer (csv)",
    resolution: "分辨率",
    batch_size: "批次大小",
    epochs: "轮数 (Epochs)",
    learning_rate: "学习率",
    optimizer: "优化器",
    precision: "精度",
    scheduler: "调度器",
    seed: "种子",
    cap_dropout: "标注 Dropout",
    save_every: "保存间隔 (Ep)",
    blocks_to_swap: "交换块数",
    grad_chkpt: "梯度检查点",
    recr_cache: "重建缓存",
    val_epochs: "验证间隔",
    val_ratio: "验证比例",
    weighting_scheme: "加权方案",
    logit_mean: "Logit 均值",
    logit_std: "Logit 标准差",
    mode_scale: "Mode 缩放",
    guidance_scale: "引导缩放",

    key: "键 (Key)",
    suffix: "后缀",
    image_key: "图片键",
    from_key: "来源键 (可选)",
    ext: "扩展名",
    image: "图片",
    include_ref: "包含参考列表",
    target: "目标",
    caption: "标注",
    reference: "参考 (可选)",
    group_key: "组键",
    sample_type: "采样类型",
    data_dir: "数据目录",
    repeats: "重复次数",
    recreate_cache_target: "目标",
    recreate_cache_ref: "参考",
    recreate_cache_cap: "标注",
    image_config_list: "图片配置列表",
    caption_config_list: "标注配置列表",
    target_config_list: "目标配置列表",
    reference_config_list: "参考配置列表",
    batch_config_list: "批次配置列表",
    training_set_list: "训练集列表",
    from_script: "来自脚本",
    from_dataset: "来自数据集",
    from_ds_list: "来自数据集列表",
    from_list: "来自列表",
    from_group: "来自组",
    from_root: "来自根节点",
    from_item: "来自项",
    to_dir: "到目录",
    to_lora: "到LoRA",
    to_misc: "到杂项",
    to_template: "到模板",
    to_ds_list: "到数据集列表",
    to_old_schema: "到旧版架构",
    connect_items: "从此处连接项。",
    connect_multiple: "从此处连接多个数据集。",
    paste_template: "粘贴基础 JSON 或选择模板以合并默认值。",
    item: "项",
    dataset: "数据集",
    add_slot: "添加插槽",
    add_source: "添加来源",
    advanced_settings: "高级设置",
    ref_config_key: "参考配置键",
    resize: "调整大小",
    min_len: "最小长度",
    dropout: "丢弃率",
    count: "数量",
    instruction: "指令 (Instruction)",
    noised: "加噪 (Noised)",
    captions_selection_target: "标注目标",

    // New specific labels
    image_name: "图片名称",
    target_name: "目标名称",
    from_image: "来自图片",
    reference_name: "参考名称",
    caption_name: "标注名称",
    
    // Workflow Panel
    workflow_panel: "工作流面板",
    current_workflow: "当前工作流",
    save_current: "保存",
    save_as_template: "另存为模板",
    available_templates: "可用模板",
    search_templates: "搜索模板...",
    loading_templates: "正在加载模板...",
    no_templates_found: "未找到模板",
    load: "加载",
    delete_template: "删除模板",
    enter_template_name: "输入模板名称:",
    confirm_clear_nodes: "确定要清除所有节点吗？",
    confirm_delete_template: "确定要删除 \"{templateName}\" 吗？",
    
    // Contact Information Labels
    twitter: "推特",
    email: "邮箱",
    qq_group: "QQ群",
    wechat_id: "微信ID",
    civitai: "CivitAI",
    bilibili: "哔哩哔哩",
    
    // About Panel Content
    t2itrainer_repository: "T2ITrainer 仓库",
    contact_information: "联系信息",
    sponsor_message: "赞助我以支持更多开源项目",
    buy_me_a_coffee: "请我喝咖啡",
    wechat: "微信",
    node_documentation: "节点文档",
    documentation_description: "以下文档详细介绍了编辑器中每种节点类型的输入和配置字段。",
    core_nodes: "核心节点",
    structure_nodes: "结构节点（新架构）",
    component_nodes: "组件节点",
    old_schema_nodes: "旧架构节点",
    
    // About Panel Tabs
    about_tab: "关于",
    docs_tab: "文档",
  }
};